import { createClient } from 'https://esm.sh/@supabase/supabase-js@2';
const SUPABASE_URL='https://qyssezlnlcctjpuvgdyn.supabase.co';
const SUPABASE_KEY='sb_publishable_wqG2eaov7vSGWjxWRPdm_w_EIDDtmDR';
const sb=createClient(SUPABASE_URL,SUPABASE_KEY,{auth:{persistSession:true,autoRefreshToken:true,detectSessionInUrl:true}});
const SYNC_KEYS=['planner-2026-v3-cat','orchid-memo-v1','orchid-todos-v1','orchid-shop-v1','orchid-trip-media-v2','orchid-calendar-filters-v2'];
const SPACE_KEY='orchid-active-space-v1';
let session=null,space=null,applying=false,lastRemote='',pushTimer=null;
const $=s=>document.querySelector(s);
const snapshot=()=>Object.fromEntries(SYNC_KEYS.map(k=>[k,localStorage.getItem(k)]));
function applyData(data){applying=true;for(const k of SYNC_KEYS){if(Object.prototype.hasOwnProperty.call(data||{},k)){const v=data[k];v===null?localStorage.removeItem(k):localStorage.setItem(k,v)}}applying=false}
function css(){if($('#orchidCloudStyle'))return;const s=document.createElement('style');s.id='orchidCloudStyle';s.textContent=`.oc-overlay{position:fixed;inset:0;z-index:90;background:#fff8f5f2;backdrop-filter:blur(12px);display:flex;align-items:center;justify-content:center;padding:20px}.oc-card{width:min(430px,100%);background:#fffefa;border:1px solid #efdde2;border-radius:26px;padding:22px;box-shadow:0 20px 60px #765b6530;color:#5a474d}.oc-card h2{margin:0 0 6px}.oc-row{display:flex;gap:8px}.oc-card input,.oc-card select{width:100%;padding:12px;border:1px solid #efdde2;border-radius:14px;background:white;margin:6px 0 10px}.oc-primary,.oc-secondary{border-radius:14px;padding:11px 14px;border:0}.oc-primary{background:#765b65;color:white}.oc-secondary{background:#fff;border:1px solid #efdde2;color:#5a474d}.oc-note{font-size:12px;color:#9b848c;line-height:1.6}.oc-cloudbar{position:fixed;left:14px;bottom:18px;z-index:20;display:flex;gap:7px;align-items:center}.oc-pill{border:1px solid #efdde2;background:#fffefa;color:#5a474d;border-radius:16px;padding:8px 11px;box-shadow:0 5px 16px #765b6525}.oc-status{font-size:11px;color:#9b848c;background:#fffaf7df;padding:5px 8px;border-radius:10px}.oc-space{padding:10px;border:1px solid #efdde2;border-radius:14px;margin:7px 0;display:flex;justify-content:space-between;gap:8px;align-items:center}.oc-space b{display:block}.oc-error{color:#b84f67;font-size:12px;min-height:18px}`;document.head.appendChild(s)}
function overlay(html){let o=$('#orchidCloudOverlay');if(!o){o=document.createElement('div');o.id='orchidCloudOverlay';o.className='oc-overlay';document.body.appendChild(o)}o.innerHTML=`<div class="oc-card">${html}</div>`;return o}
function closeOverlay(){const o=$('#orchidCloudOverlay');if(o)o.remove()}
function authView(msg=''){const o=overlay(`<h2>🐾 Orchid's Schedule</h2><div class="oc-note">登入後即可跨裝置同步，並和另一位成員共用同一份行事曆。</div><div style="margin-top:14px"><input id="ocEmail" type="email" autocomplete="email" placeholder="Email"><input id="ocPassword" type="password" autocomplete="current-password" placeholder="密碼（至少 6 碼）"><div id="ocError" class="oc-error">${msg}</div><div class="oc-row"><button id="ocLogin" class="oc-primary" style="flex:1">登入</button><button id="ocSignup" class="oc-secondary" style="flex:1">建立帳號</button></div></div>`);$('#ocLogin').onclick=async()=>{const e=$('#ocEmail').value.trim(),p=$('#ocPassword').value;$('#ocError').textContent='登入中…';const {error}=await sb.auth.signInWithPassword({email:e,password:p});if(error)$('#ocError').textContent=error.message};$('#ocSignup').onclick=async()=>{const e=$('#ocEmail').value.trim(),p=$('#ocPassword').value;$('#ocError').textContent='建立帳號中…';const {data,error}=await sb.auth.signUp({email:e,password:p});if(error)return $('#ocError').textContent=error.message;if(!data.session)$('#ocError').textContent='註冊完成，請到 Email 點確認信後再回來登入。'};return o}
async function listSpaces(){const {data,error}=await sb.rpc('list_my_schedule_spaces');if(error)throw error;return data||[]}
function spaceHub(spaces,msg=''){const joinFromUrl=new URL(location.href).searchParams.get('join')||'';overlay(`<h2>🏠 共用空間</h2><div class="oc-note">你可以建立自己的空間，或輸入共用碼加入對方的 Orchid's Schedule。</div><div id="ocSpaces" style="margin-top:12px">${spaces.map(s=>`<div class="oc-space"><div><b>${s.space_name}</b><span class="oc-note">${s.role==='owner'?'擁有者':s.role==='editor'?'可編輯':'僅檢視'} ・ ${s.share_code}</span></div><button class="oc-secondary" data-space="${s.space_id}">進入</button></div>`).join('')||'<div class="oc-note">目前還沒有共用空間。</div>'}</div><hr style="border:0;border-top:1px solid #efdde2;margin:16px 0"><input id="ocSpaceName" placeholder="新空間名稱" value="Orchid's Schedule"><button id="ocCreateSpace" class="oc-primary" style="width:100%">＋ 建立共用空間</button><div style="height:10px"></div><input id="ocJoinCode" placeholder="輸入 12 碼共用碼" value="${joinFromUrl}"><button id="ocJoinSpace" class="oc-secondary" style="width:100%">加入共用空間</button><div id="ocSpaceError" class="oc-error">${msg}</div><div style="margin-top:10px"><button id="ocLogout" class="oc-secondary">登出</button></div>`);document.querySelectorAll('[data-space]').forEach(b=>b.onclick=()=>activateSpace(b.dataset.space));$('#ocCreateSpace').onclick=async()=>{const n=$('#ocSpaceName').value.trim()||"Orchid's Schedule";$('#ocSpaceError').textContent='建立中…';const {data,error}=await sb.rpc('create_schedule_space',{p_name:n});if(error)return $('#ocSpaceError').textContent=error.message;await activateSpace(data[0].space_id,true)};$('#ocJoinSpace').onclick=async()=>{const c=$('#ocJoinCode').value.trim().toUpperCase();$('#ocSpaceError').textContent='加入中…';const {data,error}=await sb.rpc('join_schedule_space',{p_share_code:c});if(error)return $('#ocSpaceError').textContent='找不到這個共用碼，請再確認。';await activateSpace(data[0].space_id)};$('#ocLogout').onclick=()=>sb.auth.signOut()}
async function activateSpace(id,seedLocal=false){const {data:spaces}=await sb.rpc('list_my_schedule_spaces');space=(spaces||[]).find(x=>x.space_id===id);if(!space)return;localStorage.setItem(SPACE_KEY,id);const {data:doc,error}=await sb.from('schedule_space_documents').select('data,updated_at').eq('space_id',id).single();if(error)throw error;const empty=!doc.data||Object.keys(doc.data).length===0;if(seedLocal&&empty){await sb.from('schedule_space_documents').update({data:snapshot()}).eq('space_id',id);lastRemote=new Date().toISOString()}else if(empty){await sb.from('schedule_space_documents').update({data:snapshot()}).eq('space_id',id)}else{applyData(doc.data);lastRemote=doc.updated_at||''}closeOverlay();installBar();setTimeout(()=>location.reload(),250)}
function installBar(){if($('#ocCloudBar'))return;const d=document.createElement('div');d.id='ocCloudBar';d.className='oc-cloudbar';d.innerHTML='<button id="ocSpaceBtn" class="oc-pill">☁️ 空間</button><span id="ocCloudStatus" class="oc-status">☁️ 已同步</span>';document.body.appendChild(d);$('#ocSpaceBtn').onclick=async()=>spaceHub(await listSpaces())}
function setStatus(t){const e=$('#ocCloudStatus');if(e)e.textContent=t}
async function push(){if(!session||!space||applying)return;try{const now=new Date().toISOString();const {error}=await sb.from('schedule_space_documents').update({data:snapshot(),updated_at:now}).eq('space_id',space.space_id);if(error)throw error;lastRemote=now;setStatus('☁️ 已同步')}catch{setStatus('☁️ 同步失敗')}}
function queuePush(){clearTimeout(pushTimer);pushTimer=setTimeout(push,700)}
function hookStorage(){const raw=localStorage.setItem.bind(localStorage);localStorage.setItem=(k,v)=>{raw(k,v);if(SYNC_KEYS.includes(k)&&!applying)queuePush()}}
async function poll(){if(!session||!space||document.hidden)return;const {data}=await sb.from('schedule_space_documents').select('data,updated_at').eq('space_id',space.space_id).single();if(data?.updated_at&&lastRemote&&data.updated_at!==lastRemote){lastRemote=data.updated_at;applyData(data.data||{});setStatus('☁️ 收到更新');setTimeout(()=>location.reload(),350)}}
async function shareCurrent(){if(!space)return;const u=new URL(location.href);u.searchParams.set('join',space.share_code);try{await navigator.clipboard.writeText(u.toString());alert(`共用網址已複製\n共用碼：${space.share_code}`)}catch{prompt('把這個共用網址傳給對方：',u.toString())}}
async function boot(){css();const {data:{session:s}}=await sb.auth.getSession();session=s;if(!session){authView();return}const spaces=await listSpaces();if(!spaces.length){spaceHub(spaces);return}const saved=localStorage.getItem(SPACE_KEY);space=spaces.find(x=>x.space_id===saved)||spaces[0];const {data:doc}=await sb.from('schedule_space_documents').select('data,updated_at').eq('space_id',space.space_id).single();if(doc){const empty=!doc.data||Object.keys(doc.data).length===0;if(empty)await sb.from('schedule_space_documents').update({data:snapshot()}).eq('space_id',space.space_id);else applyData(doc.data);lastRemote=doc.updated_at||''}installBar();const b=$('#ocSpaceBtn');b.textContent='☁️ '+space.space_name;b.ondblclick=shareCurrent;hookStorage();setInterval(poll,8000);const join=new URL(location.href).searchParams.get('join');if(join&&join!==space.share_code){const {data,error}=await sb.rpc('join_schedule_space',{p_share_code:join.toUpperCase()});if(!error&&data?.[0]){const u=new URL(location.href);u.searchParams.delete('join');history.replaceState({},'',u);await activateSpace(data[0].space_id)}}}
sb.auth.onAuthStateChange((_e,s)=>{session=s;if(!s)authView();else setTimeout(boot,150)});window.OrchidCloud={share:shareCurrent,spaces:async()=>spaceHub(await listSpaces())};window.addEventListener('load',boot,{once:true});
